// <auto-generated />
namespace Dieting_Do.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class animalandspeciesentities : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(animalandspeciesentities));
        
        string IMigrationMetadata.Id
        {
            get { return "202106241209145_animalandspeciesentities"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
